//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.17 at 05:06:19 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ayers.io/courses", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.ayers.courses;
